### ISSUE TITLE
Error : Not able to connect thing and companion app

### ISSUE THREAD

**Issue by dpnkrg** [leinardi/androidthings-kuman-sm9#3]
How to solve this :

`I/FirebaseInitProvider: FirebaseApp initialization unsuccessful`
`I/InstantRun: starting instant run server: is main process`
`D/vndksupport: Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.`
`Google API connection failed: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(8050), resolution=null, message=null}`

**Comment by leinardi** [comment]
I fear this is a new problem that started happening recently using Android Things. Here we have the same issue: https://github.com/Nilhcem/nearby-connections-api-sample-things/issues/1

Currently I can't check it, I will update the issue if I manage to solve it.

**Comment by dpnkrg** [comment]
@leinardi waiting for your reply. 
If i downgrade the Android Things version and try, it will be good or not?

**Comment by leinardi** [comment]
can't really say without trying, and I can't right now. But if you do it
let me know.

Il mer 24 ott 2018, 21:05 Deepankar Gupta <notifications@github.com> ha
scritto:

**Comment by dpnkrg** [comment]
not able to found previous versions of android things.

**Comment by dpnkrg** [comment]
i had tried with Android Things 1.0.0. Exception not occur in version 1.0.0.
